### PR TITLE
Issue #31 - Force ES 1.7.1 for Travis

### PR DESCRIPTION
**Pull request by krozett**

### CODE REVIEW

**Comment by krozett** [comment]
Getting closer, but elasticsearch seems to think that the 'next' index doesn't exist, the one specified in config/initializers/elasticsearch.rb. Any ideas? I have no idea how ES builds its indices in the first place.

**Comment by joshuaselsky** [comment]
IIRC the original index is build when the DB is seeded using idioms like `after_save` in the model classes.

**Comment by krozett** [comment]
@joshuaselsky but what is causing it to fail now when it worked before? Is the index_name in the ES config different than a regular index? I understand indices on objects, but what is the "next" index_name in the config?

**Comment by joshuaselsky** [comment]
All of the initial ES details were added with this commit:
https://github.com/universityofcalifornia/NeXt/commit/eea4c169c118c7962d7d07ae538fa75e7b5148ba  

The index name is similar to a table name in a database. It basically gives a name to a collection of data that you can add to and search. It may be that ES creates an index referenced by the `index_name` the first time that name is referenced.   

The only thing that has changed regarding ES since that original commit is that we can now override the ES properties using YAML.   

The original usage of the index_name property is here: https://github.com/universityofcalifornia/NeXt/commit/eea4c169c118c7962d7d07ae538fa75e7b5148ba#diff-6e42962516179770cff5c2154c51baedR7

**Comment by krozett** [comment]
Okay, think I finally got it. Thanks for your help, @joshuaselsky. I read the API docs and managed to add a check to see if the index_name exists first, and creates it if it doesn't.

It's kind of a mess, but I'm not sure what best practices are for config files in Rails apps. All I know is `rake test` doesn't run `config.ru`, but it does run the initializers, so that's where I put the reindexing code. I'd really like to get rid of the hard-coded object list, in case we decide to add indices for other objects too. It should just be automatic. But for now I'm just trying to fix the build.

**Comment by joshuaselsky** [comment]
This new Travis issue is interesting. I pinned the version of WebBlocks to 2.0.4.dev in Gemfile.lock in a previous commit.  

It looks like this line is failing to retrieve the specific tag when Travis pulls down the repo.

> Fetching https://github.com/WebBlocks/WebBlocks.git

`git fetch` will retrieve the tags so it is possible that the "Fetching" in the above line means something other than `git fetch`!  I will introduce a commit that changes the actual Gemfile, but I think we can ignore this failing test here because I pulled down the tip of fork represented by this PR and the app runs successfully.

**Pull request merged**
