### PR TITLE
Fixes to Events

### LINKED ISSUE #147: Editing Event Description doesn't work
I created an event with just the Name, 

That worked, then I went back in to edit the description, but the update button is disabled...

### LINKED ISSUE #148: Events Bug:  End date does not open up the calendar picker
Events Bug:  End date does not open up the calendar picker

### PR DESCRIPTION
**Pull request by ebollens**
This pull request makes the following changes to events:

* fixes #147 so submit button is no longer disabled on edit
* fixes #148 so end date datetimepicker is applied correctly
* fix bug with start/end date not being applied to datetimepicker
* fix bug with `#create` and `#update` not accepting correct end date name
* modify description to be a WYSIWYG editor
* improve basic presentation of events

### CODE REVIEW

**Comment by ebollens** [comment]
@krozett can you review this? I'm going to fix the merge conflict.

**Comment by ebollens** [comment]
Okay, no more merge conflict here :smile:

**Comment by krozett** [comment]
@ebollens could you remove the the line `attr_accessor :end_date_time, :start_date_time` from models/event.rb? It causes confusion with end_datetime and start_datetime, and columns should never need accessors.

**Comment by krozett** [comment]
@ebollens there's also 3 lines (1 you added) to models/event.rb that have no indentation but should. Just trying to keep the code clean. :snake: :smile:

**Comment by krozett** [comment]
@ebollens for app/views/events/show.html.erb, don't you need to check against nil values when you're displaying the start and end dates?

i.e. Wrap the h5 and `<p><%= @event.start_datetime.strftime('%Y-%m-%d %H:%M') %></p>` in an if block, and do the same for the stop datetime?

**Comment by krozett** [comment]
Merged since we're in a hurry, I can make the minor fixes myself if needed

**Pull request merged**
