### PR TITLE
Issues #288, #264, #265, #207, #182, #195, #194

### PR DESCRIPTION
**Pull request by shaun965**

### CODE REVIEW

**Comment by joshuaselsky** [comment]
Please add tests and then I will merge.

**Comment by joshuaselsky** [comment]
It looks like the tests are failing because you need to pull from upstream. There have been changes made to the way the DB is seeded and the way Travis is configured to run.

**Comment by joshuaselsky** [comment]
I looked into this further and the issue is that the new password validation in your User model is causing the DB seed process to fail because the seeds do not specify a password.  This is an ugly issue because the User model cannot require passwords because passwords are not provided via the Shibboleth user creation process. It seems like the best fix for this is to move the password validation into the controller layer for the local authentication process.

**Comment by krozett** [comment]
We could always add passwords to the user seeds. And if we added a flag for Shib users (which might be useful anyway) we can make the validation conditional.

What do we do about existing users that have "invalid" passwords?

**Pull request merged**
