### PR TITLE
Custom profile picture

### PR DESCRIPTION
**Pull request by shaun965**

### CODE REVIEW

**Comment by shaun965** [comment]
Please merge after I get the correct sized image from lauren

**Comment by joshuaselsky** [comment]
I checked this out locally to test and if I try to add a profile picture to my profile, I get the "The email you are trying to change to already exists" error. I didn't change my email.

**Comment by joshuaselsky** [comment]
Also, the profile image should be shown on the edit profile page after it is uploaded.

**Comment by joshuaselsky** [comment]
Manually merged in.

**Pull request closed without merging**
